name: HOUSING PRICES

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes unitários
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest tests/

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir e enviar imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-chp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-chp:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Acessar servidor e atualizar container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/mlops-chp:latest
            docker stop mlops-container || true
            docker rm mlops-container || true
            docker run -d -p 5002:5002 --name mlops-container ${{ secrets.DOCKER_USERNAME }}/mlops-chp:latest
